<?php

declare(strict_types=1);

// PHP 8.5 configuration. See README.md for setup and available options.
return [
    'timezone' => 'UTC',
    'datefmt' => 'y/m/d(D)H:i:s',
    'board' => 'b',
    'boarddesc' => 'TinyIB',
    'boardtitle' => '',
    'alwaysnoko' => false,
    'captcha' => 'simple',
    'replycaptcha' => 'simple',
    'reportcaptcha' => 'simple',
    'managecaptcha' => 'simple',
    'report' => false,
    'autohide' => 0,
    'reqmod' => '',
    'banmessage' => true,
    'updatebumped' => true,
    'spoilertext' => false,
    'spoilerimage' => false,
    'autorefresh' => 30,
    'cloudflare' => false,
    'disallowthreads' => '',
    'disallowreplies' => '',
    'index' => 'index.html',
    'logo' => '',
    'threadsperpage' => 10,
    'previewreplies' => 3,
    'truncate' => 15,
    'wordbreak' => 80,
    'expandwidth' => 85,
    'backlinks' => true,
    'catalog' => true,
    'json' => true,
    'defaultstyle' => 'futaba',
    'delay' => 30,
    'maxthreads' => 100,
    'maxreplies' => 0,
    'maxname' => 75,
    'maxemail' => 320,
    'maxsubject' => 75,
    'maxmessage' => 8000,
    'maxkb' => 2048,
    'maxkbdesc' => '2 MB',
    'thumbnail' => 'gd',
    'uploadviaurl' => false,
    'stripmetadata' => false,
    'nofileok' => false,
    'maxwop' => 250,
    'maxhop' => 250,
    'maxw' => 250,
    'maxh' => 250,
    'tripseed' => '',
    'managekey' => '',
    'adminpass' => '',
    'modpass' => '',
    'dbaccounts' => 'accounts',
    'dbbans' => 'bans',
    'dbkeywords' => 'keywords',
    'dblogs' => 'logs',
    'dbposts' => 'b_posts',
    'dbreports' => 'b_reports',
    'dbhost' => 'localhost',
    'dbport' => 3306,
    'dbusername' => '',
    'dbpassword' => '',
    'dbname' => '',
    'dbpath' => '.tinyib.db',
    'dbdriver' => 'sqlite',
    'dbdsn' => '',
    'hidefieldsop' => [],
    'hidefields' => [],
    'anonymous' => ['Anonymous'],
    'capcodes' => [
        ['Admin', 'red'],
        ['Mod', 'purple'],
    ],
    'stylesheets' => [
        'futaba' => 'Futaba',
        'burichan' => 'Burichan',
    ],
    'uploads' => [
        'image/jpeg' => ['jpg'],
        'image/pjpeg' => ['jpg'],
        'image/png' => ['png'],
        'image/gif' => ['gif'],
    ],
    'embeds' => [
        'SoundCloud' => 'https://soundcloud.com/oembed?format=json&url=TINYIBEMBED',
        'Vimeo' => 'https://vimeo.com/api/oembed.json?url=TINYIBEMBED',
        'YouTube' => 'https://www.youtube.com/oembed?url=TINYIBEMBED&format=json',
    ],
];
